# permissions for end users to view groupattachments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: groupattachment-viewer-role
rules:
- apiGroups:
  - aws-iam.redradrat.xyz
  resources:
  - groupattachments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aws-iam.redradrat.xyz
  resources:
  - groupattachments/status
  verbs:
  - get
