# permissions for end users to edit groupattachments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: groupattachment-editor-role
rules:
- apiGroups:
  - aws-iam.redradrat.xyz
  resources:
  - groupattachments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws-iam.redradrat.xyz
  resources:
  - groupattachments/status
  verbs:
  - get
