
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: groups.aws-iam.redradrat.xyz
spec:
  group: aws-iam.redradrat.xyz
  names:
    kind: Group
    listKind: GroupList
    plural: groups
    singular: group
  scope: ""
  validation:
    openAPIV3Schema:
      description: Group is the Schema for the groups API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: GroupSpec defines the desired state of Group
          properties:
            foo:
              description: Foo is an example field of Group. Edit Group_types.go to
                remove/update
              type: string
          type: object
        status:
          description: GroupStatus defines the observed state of Group
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
