
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: roles.aws-iam.redradrat.xyz
spec:
  group: aws-iam.redradrat.xyz
  names:
    kind: Role
    listKind: RoleList
    plural: roles
    singular: role
  scope: ""
  validation:
    openAPIV3Schema:
      description: Role is the Schema for the roles API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: RoleSpec defines the desired state of Role
          properties:
            createServiceAccount:
              description: CreateServiceAccount triggers the creation of an annotated
                ServiceAccount for the created role
              type: boolean
            policy:
              items:
                properties:
                  actions:
                    description: Actions holds the desired effect the statement should
                      ensure
                    items:
                      type: string
                    type: array
                  condition:
                    additionalProperties:
                      additionalProperties:
                        type: string
                      type: object
                    description: Condition specifies the circumstances under which
                      the policy grants permission
                    type: object
                  effect:
                    description: Effect holds the desired effect the statement should
                      ensure
                    type: string
                  principal:
                    description: Principal denotes an account, user, role, or federated
                      user to which you would like to allow or deny access with a
                      resource-based policy
                    type: string
                  resources:
                    description: Resources denotes an a list of resources to which
                      the actions apply. If you do not set this value, then the resource
                      to which the action applies is the resource to which the policy
                      is attached to
                    items:
                      type: string
                    type: array
                  sid:
                    description: Sid is an optional Statement ID to identify a Statement
                    type: string
                type: object
              type: array
          type: object
        status:
          description: RoleStatus defines the observed state of Role
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
